package swing;

import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.net.URL;

import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JOptionPane;
import javax.swing.LayoutStyle.ComponentPlacement;

import beadando.CBR;
import beadando.T0D04PP;

/**
 *
 * @author Katona Adam
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame.
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    /*
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MentesGomb = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Feladat = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Szemely = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Hely = new javax.swing.JTextField();
        BetoltGomb = new javax.swing.JButton();
        Ev = new javax.swing.JComboBox();
        Honap = new javax.swing.JComboBox();
        Nap = new javax.swing.JComboBox();
        Ora = new javax.swing.JComboBox();
        Perc = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MentesGomb.setText("Mentes");
        MentesGomb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MentesGombActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("Valassza ki a megfelelo ertekeket!");

        jLabel2.setText("ev");

        jLabel3.setText("Honap");

        jLabel4.setText("Nap");

        jLabel5.setText("ora");

        jLabel6.setText("Perc");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel7.setText("irja be az esemeny targyat!");

        Feladat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FeladatActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel8.setText("irja be az esemennyel kapcsolatos szemelyeket!");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel9.setText("irja be az esemennyel kapcsolatos helyszint!");

        BetoltGomb.setText("Mentett esemenyek megjelenitese");

        Ev.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Ev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EvActionPerformed(evt);
            }
        });

        Honap.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Nap.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Ora.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Perc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Hely)
                    .addComponent(Feladat)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BetoltGomb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(MentesGomb, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Szemely)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Ev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Honap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Nap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Ora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(Perc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 18, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Honap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Perc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Feladat, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Szemely, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Hely, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MentesGomb)
                    .addComponent(BetoltGomb))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
*/
    
    /**
     * Inicializalja az ablak ertekeit.
     */
    private void initComponents() {

        MentesGomb = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Ev = new javax.swing.JComboBox();
        Honap = new javax.swing.JComboBox();
        Nap = new javax.swing.JComboBox();
        Ora = new javax.swing.JComboBox();
        Perc = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        Feladat = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Hely = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Szemely = new javax.swing.JTextField();
        BetoltGomb = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MentesGomb.setText("Mentes");
        MentesGomb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MentesGombActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("Valassza ki a megfelelo ertekeket!");

        jLabel2.setText("Ev");

        jLabel3.setText("Honap");

        jLabel4.setText("Nap");

        jLabel5.setText("Ora");

        jLabel6.setText("Perc");
        //légyszi eclipseből ne használd a mavent, mert egy rakás szar. okok, sry
        Ev.setModel(new javax.swing.DefaultComboBoxModel(CBR.ev));
        
        Honap.setModel(new javax.swing.DefaultComboBoxModel(CBR.honap));
        
        Nap.setModel(new javax.swing.DefaultComboBoxModel(CBR.nap));
        
        Ora.setModel(new javax.swing.DefaultComboBoxModel(CBR.ora));
        
        Perc.setModel(new javax.swing.DefaultComboBoxModel(CBR.perc));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13));
        jLabel7.setText("Irja be az esemeny targyat!");

        Feladat.setText("");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 13)); 
        jLabel8.setText("Irja be az esemennyel kapcsolatos helyszint!");

        Hely.setText("");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 13)); 
        jLabel9.setText("Irja be az esemennyel kapcsolatos szemelyeket!");

        Szemely.setText("");

        BetoltGomb.setText("Mentett esemenyek megjelenitese");
        BetoltGomb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BetoltGombActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(Szemely, GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
        				.addComponent(Feladat, GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(BetoltGomb)
        					.addPreferredGap(ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
        					.addComponent(MentesGomb, GroupLayout.PREFERRED_SIZE, 83, GroupLayout.PREFERRED_SIZE))
        				.addGroup(layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(Ev, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addComponent(jLabel2))
        					.addGap(18)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(Honap, GroupLayout.PREFERRED_SIZE, 56, GroupLayout.PREFERRED_SIZE)
        						.addComponent(jLabel3))
        					.addGap(18)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(jLabel4)
        						.addComponent(Nap, GroupLayout.PREFERRED_SIZE, 58, GroupLayout.PREFERRED_SIZE))
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(Ora, GroupLayout.PREFERRED_SIZE, 53, GroupLayout.PREFERRED_SIZE)
        						.addComponent(jLabel5))
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(Perc, GroupLayout.PREFERRED_SIZE, 64, GroupLayout.PREFERRED_SIZE)
        						.addComponent(jLabel6)))
        				.addGroup(layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(jLabel1)
        						.addComponent(jLabel7)
        						.addComponent(jLabel8)
        						.addComponent(jLabel9))
        					.addGap(0, 30, Short.MAX_VALUE))
        				.addComponent(Hely, GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE))
        			.addContainerGap())
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jLabel1)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel2)
        				.addComponent(jLabel4)
        				.addComponent(jLabel6)
        				.addComponent(jLabel3)
        				.addComponent(jLabel5))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(Ev, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(Honap, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(Perc, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(Nap, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(Ora, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(jLabel7)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(Feladat, GroupLayout.PREFERRED_SIZE, 44, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addComponent(jLabel8)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(Hely, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jLabel9)
        			.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        			.addComponent(Szemely, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(MentesGomb)
        				.addComponent(BetoltGomb))
        			.addContainerGap())
        );
        getContentPane().setLayout(layout);

        pack();
    }
    /**
     * A mentes gomb megnyomasara atadja a swing osztaly a T0D04PP-nak a megadott ertekeket feldolgozasra. <br>
     * @param evt esemenyt kap meg.
     */
    private void MentesGombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MentesGombActionPerformed
        
//*************************
        /**
         * Tevekenyseg.
         */
    if(!Feladat.getText().isEmpty()){
        	
        JOptionPane.showMessageDialog(null, "Teendo elmentve!");
        T0D04PP tennivalo = new T0D04PP();
            
        	
        tennivalo.datum[0] = Integer.parseInt(Ev.getModel().getSelectedItem().toString());
        System.out.print(tennivalo.datum[0] +".");
        
        tennivalo.datum[1] = Integer.parseInt(Honap.getModel().getSelectedItem().toString());
        System.out.print(tennivalo.datum[1] +".");
        
        tennivalo.datum[2] = Integer.parseInt(Nap.getModel().getSelectedItem().toString());
        System.out.print(tennivalo.datum[2] +" ");
        
        tennivalo.ido[0] = Integer.parseInt(Ora.getModel().getSelectedItem().toString());
        System.out.print(tennivalo.ido[0]>9 ?  tennivalo.ido[0] +":" : "0"+tennivalo.ido[0] +":");

        tennivalo.ido[1] = Integer.parseInt(Perc.getModel().getSelectedItem().toString());
        System.out.print(tennivalo.ido[1]>9 ?  tennivalo.ido[1] : "0"+tennivalo.ido[1] );
        
        tennivalo.feladat = Feladat.getText();
        System.out.print(" [" + tennivalo.feladat +"] ");
        tennivalo.hely = Hely.getText();
        System.out.print(tennivalo.hely.isEmpty() ? "[nincs megadva hely] " : "[" + tennivalo.hely +"] ");
        tennivalo.szemely = Szemely.getText();
        System.out.print(tennivalo.szemely.isEmpty() ? "[nincs megadva szemely]" : "[" + tennivalo.szemely + "]");
        
        try {   tennivalo.Init(); } 
        catch (Exception e) {		}
        System.out.println();
        }
    else{
        JOptionPane.showMessageDialog(null, "Teendo nem lett elmentve, feladat megadasa kotelezo!");
        }
//*************************
        
    }//GEN-LAST:event_MentesGombActionPerformed
    
    /**
     * A mentett esemenyek megjelenitese gomb megnyomasara atadja a swing osztaly a <br>
     * T0D04PP-nak a megadott ertekeket feldolgozasra. <br>
     * @param evt esemenyt kap meg.
     */
    private void BetoltGombActionPerformed(java.awt.event.ActionEvent evt) {

    	URL url = getClass().getClassLoader().getResource("Dict.txt");
    	String utvonal=url.toExternalForm();
    	String utvonal2 = utvonal.replace("file:/", "");
    	
        Desktop dt = Desktop.getDesktop();
        try {
    		dt.open( new File(utvonal2) );
    	} catch (IOException e) {
    		JOptionPane.showMessageDialog(null, "A fájl még nem létezik!");
    		e.printStackTrace();
    	}
    }    
    /**
     * 
     * @param evt esemenyt kap meg.
     */
    private void FeladatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FeladatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FeladatActionPerformed

    /**
     * 
     * @param evt esemenyt kap meg.
     */
    private void EvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EvActionPerformed

    /**
     * @param args the command line arguments.
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    /**
     * Ablak tartalmat deklaralo obektum.
     */
    private javax.swing.JButton BetoltGomb;
    /**
     * Ablak tartalmat deklaralo obektum.
     */
    private javax.swing.JComboBox Ev;
    /**
     * Ablak tartalmat deklaralo obektum.
     */
    private javax.swing.JTextField Feladat;
    /**
     * Ablak tartalmat deklaralo obektum.
     */
    private javax.swing.JTextField Hely;
    /**
     * Ablak tartalmat deklaralo obektum.
     */
    private javax.swing.JComboBox Honap;
    /**
     * Ablak tartalmat deklaralo obektum.
     */
    private javax.swing.JButton MentesGomb;
    /**
     * Ablak tartalmat deklaralo obektum.
     */
    private javax.swing.JComboBox Nap;
    /**
     * Ablak tartalmat deklaralo obektum.
     */
    private javax.swing.JComboBox Ora;
    /**
     * Ablak tartalmat deklaralo obektum.
     */
    private javax.swing.JComboBox Perc;
    /**
     * Ablak tartalmat deklaralo obektum.
     */
    private javax.swing.JTextField Szemely;
    /**
     * Ablak tartalmat deklaralo obektum.
     */
    private javax.swing.JLabel jLabel1;
    /**
     * Ablak tartalmat deklaralo obektum.
     */
    private javax.swing.JLabel jLabel2;
    /**
     * Ablak tartalmat deklaralo obektum.
     */
    private javax.swing.JLabel jLabel3;
    /**
     * Ablak tartalmat deklaralo obektum.
     */
    private javax.swing.JLabel jLabel4;
    /**
     * Ablak tartalmat deklaralo obektum.
     */
    private javax.swing.JLabel jLabel5;
    /**
     * Ablak tartalmat deklaralo obektum.
     */
    private javax.swing.JLabel jLabel6;
    /**
     * Ablak tartalmat deklaralo obektum.
     */
    private javax.swing.JLabel jLabel7;
    /**
     * Ablak tartalmat deklaralo obektum.
     */
    private javax.swing.JLabel jLabel8;
    /**
     * Ablak tartalmat deklaralo obektum.
     */
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
